services:
  db:
    container_name: ojs_db
    image: postgis/postgis:17-3.5
    # postgis only supports the linux/amd64 platform
    platform: linux/amd64
    ports:
      - "15432:5432"
    volumes:
      - .data/postgres:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ojs
      POSTGRES_USER: ojs
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -U ojs -d ojs && psql -U ojs -d ojs -c 'SELECT 1;' || exit 1
      interval: 2s
      retries: 120

  app:
    container_name: ojs_app
    # image: dhil/ojs
    build:
      context: .
    platform: linux/amd64
    ports:
      - 8080:80
    volumes:
      # persistence config
      - .data/app/config.inc.php:/var/www/html/config.inc.php
      # persistence
      - .data/app/files:/var/www/files
      - .data/app/public:/var/www/html/public
      - .data/app/logs:/var/log/apache2
      # Custom theme/plugin development (override for active development)
      # - ./themes/<THEME NAME>:/var/www/html/plugins/themes/<THEME NAME>
      # - ./plugins/<PLUGIN NAME>:/var/www/html/plugins/<PLUGIN NAME>
      # demo data for import
      - ./demo-data:/demo-data
    environment:
      - DOMAIN=j1.localhost
      - JOURNAL_ACRONYM=j1
      - HTTPS=off
    depends_on:
      - db

  mail:
    container_name: ojs_mail
    image: jcalonso/mailhog:v1.0.1
    ports:
      - "8025:8025"